//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholesaleRaja.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSR_Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string SKU { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
        public decimal BasePrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> SavingsAmount { get; set; }
        public Nullable<int> SavingsPercentage { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoMetaKeywords { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DisabledDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DisabledBy { get; set; }
        public string BasePriceString { get; set; }
        public string SalePriceString { get; set; }
        public string SavingsAmountString { get; set; }
    }
}
