//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholesaleRaja.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSR_City
    {
        public int CityCode { get; set; }
        public string CityName { get; set; }
        public Nullable<int> StateCode { get; set; }
    
        public virtual WSR_State WSR_State { get; set; }
    }
}
